name: Tweet

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run tweet